Add contact management functionality: toggle sections, fetch contacts…
BrennDev/Semillero pull request #4
Opened 2024-08-15 18:40 UTC by BrennDev

**Add contact management functionality: toggle sections, fetch contacts, and handle contact creation.**

- Implement toggle visibility between contact list and contact creation form.
- Fetch and display contacts from the API with a delay.
- Add contact creation form with fields for first name, last name, company, job title, and email.
- Include form validation and POST request handling to submit new contacts.
- Render newly created contacts in the table and clear the form on successful submission.
- Handle errors for both GET and POST requests.
- Introduce utility functions for element creation, random avatar generation, and form clearing.

![exercise6](https://github.com/user-attachments/assets/531c2845-960d-4e4f-85b3-7a4ef7e9b414)

2024-08-15 19:13 UTC, josuemonroy2023 reviewed
Te dejé un comentario. Aparte de eso creo que no vi que los campos en el formulario fueran requeridos, o si pasó un error avisarle al usuario. 
No estoy muy seguro de los requerimientos, pero tal vez valdría la pena comentarlo.

2024-08-15 19:13 UTC, josuemonroy2023 commented on 09_PROJECT/src/js/app.js
> +    contacts = [...contacts, ...data.data];
Veo que la razón por la cuál la variable `contacts` es de tipo `let` es por esta forma. No sería mejor hacer un concat tal vez? O tal vez sólo agregar los valores nuevos al listado?

2024-08-19 22:34 UTC, BrennDev commented on 09_PROJECT/src/js/app.js
> +    contacts = [...contacts, ...data.data];
Listo!, se cambio la variable de `let` a `const` para garantizar que la referencia al arreglo `contacts` permanezca inmutable y no pueda ser reasignada.

2024-08-20 23:50 UTC, daini-rl requested changes

2024-08-20 23:50 UTC, daini-rl commented on 09_PROJECT/index.html
> +          <button id="show-contact" class="button-style button-hover">
Creo que ahora el botón de Contacts no tiene mucho sentido al estar siempre visible la tabla de contactos, creo que podrías eliminarlo y sus respectivas referencias en el js.

2024-08-21 22:27 UTC, Tecuani1 commented on 09_PROJECT/src/js/app.js
> +        contact.avatar || `https://i.pravatar.cc/150?img=${getRandomNumber()}`,
Me gusta la implementación del avatar de forma random, la verdad no sabía que existía este tipo de recursos :) pero es bueno aprender

2024-08-21 22:27 UTC, Tecuani1 commented on 09_PROJECT/src/js/app.js
> +const createElement = (tag, attributes = {}) => {
Está función me gusta por qué es muy clara y encapsula muy bien la creación de los elementos HTML

2024-08-22 16:32 UTC, daini-rl approved these changes

2024-08-23 15:38 UTC, merged